### ISSUE TITLE
No CORS header on 500 response

### ISSUE THREAD

**Issue by skddc** [5apps/liquor-cabinet#47]

**Comment by michielbdejong** [comment]
And also the fact in itself that https://storage.5apps.com/michiel2/public/notes/test.file gives a 500.

**Comment by skddc** [comment]
I already opened #48 for that.

**Comment by gregkare** [comment]
After working on #53 and #48 I understand why the 500 errors you've spotted have no CORS headers. The web server was crashing before being able to set the CORS headers in those cases.

**Comment by michielbdejong** [comment]
OK, so the issue is out of scope for liquor-cabinet then, but are you going to fix it for 5apps storage? It would be nice to display "please contact your storage provider" to the user when the client receives 5xx errors. If you don't put CORS headers on them, then the client will tell the user "your internet is down", which is an incorrect and confusing error message then.

**Comment by skddc** [comment]
The other fixes fix this, as there can be no 500s if there's no actual bug in the system.

**Comment by michielbdejong** [comment]
> there can be no 500s if there's no actual bug in the system.

:)

**Comment by michielbdejong** [comment]
There now seem to be cors headers on at least some of the 500s coming from openresty:

````js
{
  statusCode: 500,
  responseHeaders: {
        server: 'openresty',
        date: 'Mon, 23 Mar 2015 20:24:40 GMT',
        'content-type': 'text/html;charset=utf-8',
        'content-length': '30',
        connection: 'keep-alive',
        status: '500 Internal Server Error',
        'access-control-allow-origin': '*',
        'access-control-allow-methods': 'GET, PUT, DELETE',
        'access-control-allow-headers': 'Authorization, Content-Type, Origin, If-Match, If-None-Match',
        'access-control-expose-headers': 'ETag, Content-Length',
        'cache-control': 'no-cache',
        expires: '0'
  },
  responseBody: '<h1>Internal Server Error</h1>'
}
````

**Comment by skddc** [comment]
How did you manage to get another 500? :(

**Comment by michielbdejong** [comment]
Just worked it out, issue is here: #56
