### ISSUE TITLE
Unprocessable entity

### ISSUE THREAD

**Issue by michielbdejong** [5apps/liquor-cabinet#49]
When I try to send 'asdf' as the Content-Type, it disobeys my wish and desire, and response with a 422 Unprocessable Entity error.

I think a remoteStorage server should be agnostic about the body and the Content-Type and treat them both as opaque blobs. It should work as a filesystem and not "process" my data in any way, right?

**Comment by skddc** [comment]
Yes, we're doing this in addition to the protocol, so you can't shoot yourself in the foot like that. Nobody ever said that it prevented them from doing actual app development, so we're leaving it for now, as we think it's better to not allow it.

**Comment by michielbdejong** [comment]
So you whitelist which values may be passed as Content-Type? Can you publish this whitelist?

**Comment by skddc** [comment]
I don't remember off the top of my head, it's probably Riak. If you ever find a single valid content type that doesn't work, please let us know. Nobody ever had one.

**Comment by skddc** [comment]
Also, this might change soon, due to our upcoming switch to Swift.

**Comment by michielbdejong** [comment]
fwiw, https://tools.ietf.org/html/rfc7230#section-3.2.4 prescribes a 400 if a header value contains newlines.

I created a spec issue about it, proposing to  allow both 400 and 422. We can discuss there if Content-Type restrictions (other than restricting them to US-ASCII and not too long), is a good idea for remoteStorage servers in general.

**Comment by skddc** [comment]
Cool.
