### ISSUE TITLE
Expose Content-Length header

### ISSUE THREAD

**Issue by michielbdejong** [5apps/liquor-cabinet#50]
When testing https://github.com/michielbdejong/ludbud in Chromium, I get:

````
Refused to get unsafe header "Content-Length"
````

Could you add it to Access-Control-Expose-Headers?

See also http://blog.import.io/tech-blog/exposing-headers-over-cors-with-access-control-expose-headers

**Comment by gregkare** [comment]
I've added it and deployed to production, the header is now `Access-Control-Expose-Headers: ETag, Content-Length`.
