### ISSUE TITLE
Reproducible 500 error, also with non-empty body

### ISSUE THREAD

**Issue by michielbdejong** [5apps/liquor-cabinet#53]
Apart from https://github.com/5apps/liquor-cabinet/pull/51 which is about empty documents, there is a reproducable 500 error doing a 'HEAD' request on a document containing'asdf', you can reproduce this by visiting https://ludbud.5apps.com/ (you see more info in Chrome dev tools than in Firefox ones).

Interestingly, the response to the PUT request also has two status headers (maybe this has something to do with what goes wrong?).

![500-error-on-head](https://cloud.githubusercontent.com/assets/408412/6627199/a487ca08-c8fc-11e4-8e96-ca1f49d9ea91.png)
![double-status-header-on-put](https://cloud.githubusercontent.com/assets/408412/6627200/a489f60c-c8fc-11e4-8e83-e064985b436c.png)

**Comment by gregkare** [comment]
Thanks for the report. I could reproduce it on our staging server, I'm working on a fix for it.

**Comment by skddc** [comment]
Fixed and deployed.

I can't see any errors in the console anymore.
