### ISSUE TITLE
Count storage overall size in Redis

### ISSUE THREAD

**Issue by skddc** [5apps/liquor-cabinet#81]
In order to use a single container in Swift, we need to count size somewhere else. As we already store metadata in Redis and use it for traffic stats as well, I think it makes sense to incr/decr a key for it from LQ.

I think we can't do it from our load-balancer Lua module, because we don't know the size difference of PUTs to existing docs there. But let me know if I'm missing something and that's possible after all.

**Comment by skddc** [comment]
This is blocking the move to a single container currently.

**Comment by skddc** [comment]
@galfert Any luck with this on the train on Friday?

**Comment by galfert** [comment]
Yes, I think I got it working. At least the tests say so :)

I couldn't test this for real in the VM yet though, as I had to stand for the whole second leg of the train ride because it was so packed :(

I will give it a try right now.

**Comment by skddc** [comment]
Ok. Please push your branches at the end of the day in the future. It's not nice to keep code from review for no other reason that thinking it has to be bugfree or perfect from the first push. I could've actually tested and reviewed it during the weekend.
