### ISSUE TITLE
Support content-range requests

### ISSUE THREAD

**Issue by skddc** [5apps/liquor-cabinet#82]
Should also be announced in the Webfinger response, as per https://tools.ietf.org/html/draft-dejong-remotestorage-06#section-10

**Comment by skddc** [comment]
Note: Swift supports it. Not sure about handling that stuff in LQ.

**Comment by skddc** [comment]
I just added audio and video playback to Inspektor (not deployed yet), and it's a pretty abysmal experience without this feature. Even if the entire file has been loaded, you still cannot skip forward at all.

**Comment by gregkare** [comment]
I'm giving this one a try, S3/Exoscale SOS also supports it. I'll report my findings here
